### ISSUE TITLE
こうかとん即死バグの危険性

### ISSUE THREAD

**Issue by a123ktx** [c0b21145/ProjExD#11]
https://github.com/c0b21145/ProjExD/blob/8c04b4f672427c23f1e5ba5832a0c63aad0949cc/ex04/dodge_bomb.py#L45
爆弾がこうかとんの上に発生すると1/1000fpsで残基が削れてしまいます
こうかとんが出現しない範囲に爆弾を設定するのが安全かもです

**Comment by c0b21145** [comment]
爆弾の初期位置を変更する事でこうかとんが即死する事を回避しました。
